
# levantar db y api
services:
  api:
    build: .
    container_name: go-api
    ports:
      - "8080:8080"
    depends_on: 
      - db    # espera a que el servicio db esté listo antes de iniciar api
  
  db:
    image: postgres:15
    container_name: db-postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=midb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: