// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type ListaProducto struct {
	ID         int32
	IDProducto int32
	Cantidad   int32
	Comprado   sql.NullBool
}

type Producto struct {
	ID          int32
	Titulo      string
	Descripcion string
}
